name: trice
description:
  This platform brings all the  organizations  Safaricom, Airtel … and news agencies
  NTV, Citizen, KTN … into one place. Here these organizations can write information about their
  products and you can get news from your favorite television station.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  flutter_svg: ^1.1.6
  overlay_support: ^2.1.0

  # Modules
  common:
    path: core/common
  di:
    path: core/di
  domain:
    path: core/domain
  model:
    path: core/model
  agrich:
    path: feature/agrich
  cart:
    path: feature/cart
  cuisine_detail:
    path: feature/cuisine_detail
  delivery:
    path: feature/delivery
  wallet:
    path: feature/wallet
  instore:
    path: feature/instore

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/todo.svg
    - assets/icons/comments.svg
