name: trice
description:
  This platform brings all the  organizations  Safaricom, Airtel … and news agencies
  NTV, Citizen, KTN … into one place. Here these organizations can write information about their
  products and you can get news from your favorite television station.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5

  # Modules
  common:
    path: core/common
  sign_up:
    path: feature/sign_up
  di:
    path: core/di
  domain:
    path: core/domain
  log_in:
    path: feature/log_in
  hi_cars:
    path: feature/hi_cars
  apartment:
    path: feature/apartment
  tasks:
    path: feature/tasks
  agrich:
    path: feature/agrich
  e_solar:
    path: feature/e_solar
  cuisine_detail:
    path: feature/cuisine_detail
  model:
    path: core/model

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/todo.svg
    - assets/icons/comments.svg
