name: trice
description:
  An e-commerce platform for a foodstore.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  overlay_support: ^2.1.0

  # Modules
  common:
    path: core/common
  di:
    path: core/di
  domain:
    path: core/domain
  model:
    path: core/model
  agrich:
    path: feature/agrich
  cart:
    path: feature/cart
  cuisine_detail:
    path: feature/cuisine_detail
  delivery:
    path: feature/delivery
  wallet:
    path: feature/wallet

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.4.2
  build_runner: ^2.4.6
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
