name: common
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  google_fonts: ^3.0.1
  slider_button: ^2.0.0
  image_picker: ^0.8.6
  flutter_svg: ^1.1.6
  fluttertoast: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/icons/duplicate.svg
