// Mocks generated by Mockito 5.4.2 from annotations
// in model/test/src/messagebird_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:model/src/messagebird_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MessageBird].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageBird extends _i1.Mock implements _i2.MessageBird {
  @override
  String get channelId => (super.noSuchMethod(
        Invocation.getter(#channelId),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);

  @override
  String get to => (super.noSuchMethod(
        Invocation.getter(#to),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);

  @override
  String get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);

  @override
  String get text => (super.noSuchMethod(
        Invocation.getter(#text),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);

  @override
  Map<String, dynamic> toFirestore() => (super.noSuchMethod(
        Invocation.method(
          #toFirestore,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
