// Mocks generated by Mockito 5.4.2 from annotations
// in model/test/src/restaurant_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:model/src/restaurant.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [Restaurant].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestaurant extends _i1.Mock implements _i2.Restaurant {
  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);

  @override
  String get locationName => (super.noSuchMethod(
        Invocation.getter(#locationName),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);

  @override
  String get locationCoordinate => (super.noSuchMethod(
        Invocation.getter(#locationCoordinate),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);

  @override
  Map<String, dynamic> toFirestore() => (super.noSuchMethod(
        Invocation.method(
          #toFirestore,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
