// Mocks generated by Mockito 5.4.2 from annotations
// in model/test/src/subscription_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:model/src/subscription.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [Subscription].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscription extends _i1.Mock implements _i2.Subscription {
  @override
  String get shippingInfo => (super.noSuchMethod(
        Invocation.getter(#shippingInfo),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);

  @override
  bool get shippingStatus => (super.noSuchMethod(
        Invocation.getter(#shippingStatus),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get minShipAmount => (super.noSuchMethod(
        Invocation.getter(#minShipAmount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get executivePrice => (super.noSuchMethod(
        Invocation.getter(#executivePrice),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get elitePrice => (super.noSuchMethod(
        Invocation.getter(#elitePrice),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  Map<String, String> get executiveBenefits => (super.noSuchMethod(
        Invocation.getter(#executiveBenefits),
        returnValue: <String, String>{},
        returnValueForMissingStub: <String, String>{},
      ) as Map<String, String>);

  @override
  Map<String, String> get eliteBenefits => (super.noSuchMethod(
        Invocation.getter(#eliteBenefits),
        returnValue: <String, String>{},
        returnValueForMissingStub: <String, String>{},
      ) as Map<String, String>);

  @override
  String get contact => (super.noSuchMethod(
        Invocation.getter(#contact),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);

  @override
  Map<String, dynamic> toFirestore() => (super.noSuchMethod(
        Invocation.method(
          #toFirestore,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
