name: network
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  firebase_storage: ^11.0.10
  cloud_firestore: ^4.3.1
  typesense: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
