name: Release

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Build release APK
      run: flutter build apk --release

    - name: Sign release APK
      run: jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ${{ secrets.KEYSTORE_FILE }} build/app/outputs/apk/release/app-release.apk ${{ secrets.ALIAS_NAME }}

    - name: Upload to App Center
      uses: microsoft/appcenter-action@v1
      with:
        appcenter_token: ${{ secrets.APPCENTER_TOKEN }}
        app_name: 'Trice'
        owner_name: '_TRICE'
        distribution_group: 'Beta'
        apk_path: 'build/app/outputs/apk/release/app-release.apk'
